### ISSUE TITLE
Tokens/s stat and generation time

### ISSUE THREAD

**Issue by RookieIndieDev** [Mobile-Artificial-Intelligence/maid#206]
Tokens per second and the amount of time it took to generate response would be good metrics to have.

**Comment by danemadsen** [comment]
Ok Timings are now logged in settings along with a bunch of other llama.cpp info

**Comment by RookieIndieDev** [comment]
Available in the 1.15 release?

**Comment by danemadsen** [comment]
> Available in the 1.1.5 release?

No. Will be available in 1.1.6

till then you can download a build which it includes it from actions

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7206997709

**Comment by RookieIndieDev** [comment]
Downloaded that release, where are the stats displayed?

**Comment by danemadsen** [comment]
> Downloaded that release, where are the stats displayed? 

In the settings menu / page. The stats will display after the generation finishes
