### ISSUE TITLE
Issue with penalize_newline parameter 

### ISSUE THREAD

**Issue by iamRjarpan** [Mobile-Artificial-Intelligence/maid#211]
I am using ngrok and I saw that chat was not working and the main reason was 

```
{
    "error": "option \"penalize_newline\" must be of type boolean"
}
```
And in the request it was sending ` "penalize_newline": 1` but when I removed the parameter it was working fine. Or at least make it True or False instead of 0 or 1

![Screenshot 2023-12-13 223727](https://github.com/Mobile-Artificial-Intelligence/maid/assets/45498226/21d05983-7a5a-441c-a1e9-daefd365c56e)

**Comment by danemadsen** [comment]
Ok try this run:
https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7202157607 it should work now
