### ISSUE TITLE
Support to latest MS Phi-2 model?

### ISSUE THREAD

**Issue by danemadsen** [Mobile-Artificial-Intelligence/maid#224]
### Discussed in https://github.com/Mobile-Artificial-Intelligence/maid/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **Slavczays** December 20, 2023</sup>
Hello. First of all thanks for your great app - fantastic work. Is there any chance to add support for newest small llm models Phi-2 2.7 from Microsoft? GGUF model (quantized by the Bloke) is available at HF, but isn't compatible with your app?
Maybe it will be helpful - it looks like Phi-2 support was just recently added to Llama cpp [https://github.com/ggerganov/llama.cpp/pull/4490#pullrequestreview-1787346569](url)</div>

**Comment by Foul-Tarnished** [comment]
Phi-2 Q6_K & Q8 both crash for me, weird
