### ISSUE TITLE
Add support for MobileLLaMA/MobileVLM models

### ISSUE THREAD

**Issue by Foul-Tarnished** [Mobile-Artificial-Intelligence/maid#230]
LLM model targeted for mobile devices, available in 1.4B and 2.7B
https://github.com/Meituan-AutoML/MobileVLM

![model graph](https://github.com/Meituan-AutoML/MobileVLM/raw/main/mobilellava.png)

Apparently only "MobileLLaMA" is available right now and not "MobileVLM"

Models links :
https://huggingface.co/mtgv/MobileLLaMA-1.4B-Base
https://huggingface.co/mtgv/MobileLLaMA-1.4B-Chat

https://huggingface.co/mtgv/MobileLLaMA-2.7B-Base
https://huggingface.co/mtgv/MobileLLaMA-2.7B-Chat

**Comment by Foul-Tarnished** [comment]
Also Phi-2 Q6_K crash for me

**Comment by danemadsen** [comment]
It will be supported when a GGUF version is released and llama.cpp supports it.
