### ISSUE TITLE
Low RAM usage, low performance

### ISSUE THREAD

**Issue by Foul-Tarnished** [Mobile-Artificial-Intelligence/maid#231]
On SD865 12GB +4gb swap, I have still 7.3GB ram available with Mistral 7B
Considering android OS takes easily 2gb, it means Maid uses not even 4gb of ram

Maybe add a setting to force model to stay in ram ?

Or implement these to make it faster on devices with limited ram :

"PowerInfer"
https://huggingface.co/papers/2312.12456

"LLM in a flash"
https://huggingface.co/papers/2312.11514

**Comment by danemadsen** [comment]
Interesting, Ill have to look into it. 4GB of ram does seem to be pretty standard for a 7b model though

**Comment by danemadsen** [comment]
Implementing those papers would be something that would have to be done of llama.cpp's end, not a lot i can do here.
