### ISSUE TITLE
don't send with enter button on mobile

### ISSUE THREAD

**Issue by GameOverFlowChart** [Mobile-Artificial-Intelligence/maid#234]
I know that #226 asked for that on Desktop, but that behavior is bad on mobile because you don't have ctrl on your usual mobile keyboard and pressing the send button of the app is simple enough. So we either need an option in the settings or this feature needs to change depending on the build. I tried the latest build which isn't released, and it does add the behavior to the Android apk.

Further testing that build, it also seems to mess with the model somehow.

**Comment by danemadsen** [comment]
Ok this should work now

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7427520400

if not im reverting to how it was originally prior to #226

**Comment by GameOverFlowChart** [comment]
> Ok this should work now
> 
> https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7427520400
> 
> if not im reverting to how it was originally prior to #226

I can confirm that it works now
