### ISSUE TITLE
Bug context seem to be kept?

### ISSUE THREAD

**Issue by GameOverFlowChart** [Mobile-Artificial-Intelligence/maid#239]
The context seems to be kept even if the session is deleted and a new session is started (and no it's not because of the example dialogue saved by the character, I made sure to clean them). This bug seems to be new I didn't had this with older versions.

**Comment by danemadsen** [comment]
should be fixed now

**Comment by GameOverFlowChart** [comment]
I think the bug was gone. It's back, I stumbled upon it with this build https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7397151415

**Comment by GameOverFlowChart** [comment]
Tested again with 1.1.7 the bug is definitive present.

**Comment by danemadsen** [comment]
Can you be more discriptive with you're issue? I cannot reproduce it, whenever i switch sessions theres no issue with dropping the session

**Comment by GameOverFlowChart** [comment]
> Can you be more discriptive with you're issue? I cannot reproduce it, whenever i switch sessions theres no issue with dropping the session

Ask the model if bana is a fruit. Get the answer. Start a new session. Ask the model what your last question was. It will tell you that you asked about bananas.

**Comment by danemadsen** [comment]
Ive tried that and i get nothing. Though i ask, "tell me about bane" and then start anew session before asking what Dc character i just asked about

**Comment by GameOverFlowChart** [comment]
Are you using the app or calling the functions directly somehow? It might be that the gui doesn't call the functions to clear it?
![ZomboDroid_11012024095739](https://github.com/Mobile-Artificial-Intelligence/maid/assets/109205200/1fcb9122-eea9-410e-8d45-9aa3db6bffe4)

**Comment by danemadsen** [comment]
Give this one a shot then?

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7486491635

I cant reproduce it though so if that doesn't fix it i don't really know how to help you. Maybe try Uninstalling and reinstalling

**Comment by GameOverFlowChart** [comment]
> Give this one a shot then?
> 
> https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7486491635
> 
> I cant reproduce it though so if that doesn't fix it i don't really know how to help you. Maybe try Uninstalling and reinstalling

Reinstalling didn't help, somehow I have troubles getting any response from the version you linked

**Comment by GameOverFlowChart** [comment]
It works with 1.1.8 now.
First I got no response at all but playing around solved it. I either had to change min p since that wasn't in the parameters.json which I used or it was related with #221 because I also changed the alias to get it to work.
