### ISSUE TITLE
Option to disable the automatic addition of examples

### ISSUE THREAD

**Issue by GameOverFlowChart** [Mobile-Artificial-Intelligence/maid#240]
As it's said in the title, I prefer it to be able to add the examples manually. I need to delete them every time the way it is now.

**Comment by danemadsen** [comment]
So you want an additional way to turn off adding examples other than just deleting the examples? Why not just delete them, or is the character card resetting for you?

**Comment by GameOverFlowChart** [comment]
> So you want an additional way to turn off adding examples other than just deleting the examples? Why not just delete them, or is the character card resetting for you?

It seems like it starts to add them again sometimes. Like if you have a basic conversation with the model, that conversation is added as an example. I don't know if that's intended, I can see that some people would want this to happen but I would like to opt out.

**Comment by danemadsen** [comment]
> > So you want an additional way to turn off adding examples other than just deleting the examples? Why not just delete them, or is the character card resetting for you?
> 
> It seems like it starts to add them again sometimes. Like if you have a basic conversation with the model, that conversation is added as an example. I don't know if that's intended, I can see that some people would want this to happen but I would like to opt out.

Its not ment to add the conversation to the examples, if its still doing that its an error. I believe I fixed that though

**Comment by GameOverFlowChart** [comment]
> > > So you want an additional way to turn off adding examples other than just deleting the examples? Why not just delete them, or is the character card resetting for you?
> > 
> > 
> > It seems like it starts to add them again sometimes. Like if you have a basic conversation with the model, that conversation is added as an example. I don't know if that's intended, I can see that some people would want this to happen but I would like to opt out.
> 
> Its not ment to add the conversation to the examples, if its still doing that its an error. I believe I fixed that though

I see, let's hope it's fixed, I didn't try anything newer than 1.1.6 till now.

**Comment by danemadsen** [comment]
> > > > So you want an additional way to turn off adding examples other than just deleting the examples? Why not just delete them, or is the character card resetting for you?
> > > 
> > > 
> > > It seems like it starts to add them again sometimes. Like if you have a basic conversation with the model, that conversation is added as an example. I don't know if that's intended, I can see that some people would want this to happen but I would like to opt out.
> > 
> > 
> > Its not ment to add the conversation to the examples, if its still doing that its an error. I believe I fixed that though
> 
> I see, let's hope it's fixed, I didn't try anything newer than 1.1.6 till now.

give this build a try

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7397151415

I found that the adding of the conversation to the examples occurred only after 2 message exchanges and the user regenerates.

**Comment by GameOverFlowChart** [comment]
> > > > > So you want an additional way to turn off adding examples other than just deleting the examples? Why not just delete them, or is the character card resetting for you?
> > > > 
> > > > 
> > > > It seems like it starts to add them again sometimes. Like if you have a basic conversation with the model, that conversation is added as an example. I don't know if that's intended, I can see that some people would want this to happen but I would like to opt out.
> > > 
> > > 
> > > Its not ment to add the conversation to the examples, if its still doing that its an error. I believe I fixed that though
> > 
> > 
> > I see, let's hope it's fixed, I didn't try anything newer than 1.1.6 till now.
> 
> give this build a try
> 
> https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7397151415
> 
> I found that the adding of the conversation to the examples occurred only after 2 message exchanges and the user regenerates.

I downloaded it after writing that comment and for now it seems to work fine. I did not use the regenerate button that often since it was buggy at first and is also slow so there might be something else that also triggers it. But what I have found with this build is that #234 still is an issue, enter on the keyboard sends the text on Android.

**Comment by danemadsen** [comment]
I just tested it and I cant see how #234 is still an issue? Are you wanting to be able to send the prompt on clicking enter on android? That's not typical for a chat app?

**Comment by GameOverFlowChart** [comment]
> I just tested it and I cant see how #234 is still an issue? Are you wanting to be able to send the prompt on clicking enter on android? That's not typical for a chat app?

Nope, as I said on mobile pressing the dedicated send button is easy (on PC you need to switch from keyboard to mouse) so having the enter button to do the same brings you nothing. On PC you can use ctrl + enter to start a new line. You can't do this on mobile without a CTRL button. So for both platforms different behaviors make sense.
I'm using different chat apps like session, or WhatsApp and in all of them, enter starts a new line. New lines help structuring longer text, making them more readable.
For example, I want to give the model a new instruction and data to to work with. I write the instruction, I press enter to separate the data from the instruction and... the app sends the unfinished message to the model.
Sending with enter only makes sense if you are chatting in realtime, exchanging short and quick messages, if the conversation is asynchronous and you want to send more information at once (and the model is slow and needs it's time) it's better to be able to format it properly before sending it.

**Comment by danemadsen** [comment]
Ok im not sure why thats the case on your phone. Enter starts a new line on my device. Maybe try uninstalling and reinstalling

**Comment by GameOverFlowChart** [comment]
> Ok im not sure why thats the case on your phone. Enter starts a new line on my device. Maybe try uninstalling and reinstalling

Nope uninstalling doesn't help, it did work perfectly fine with the old versions of the app
