### ISSUE TITLE
TTS chat feature request 

### ISSUE THREAD

**Issue by x-legion** [Mobile-Artificial-Intelligence/maid#244]
Implement Android native TTS for dyslexic people. Kind of like how Google Bard is doing.

**Comment by danemadsen** [comment]
not sure if Android TTS works on all platforms and im not really interested in implementing too much platform specific code. But ill look into it

**Comment by Ar57m** [comment]
would be nice, I would love to use it with [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx)

**Comment by danemadsen** [comment]
I can use https://pub.dev/packages/flutter_tts and it will be ok for all platforms (excluding linux maybe) but to be perfectly honest im kind of waiting for there so be a decent open source alternative to something like eleven labs that i can implement

**Comment by x-legion** [comment]
> I can use https://pub.dev/packages/flutter_tts and it will be ok for all platforms (excluding linux maybe) but to be perfectly honest im kind of waiting for there so be a decent open source alternative to something like eleven labs that i can implement

I  use this app primarily on Android only. Windows and Linux have better alternatives to this. Maybe you can fork some code from here for Android. https://github.com/jing332/tts-server-android

**Comment by danemadsen** [comment]
For anyone interested and so nobody try to take this on by going in a different direction. The current plan is to use piper_tts for text to speech but i haven't finished developing it yet.

https://github.com/Mobile-Artificial-Intelligence/piper_tts

**Comment by lee-b** [comment]
Worth noting that LocalAI supports basically all of the OpenAI API, but locally.  That includes multiple models, text to speech, speech to text, image generation, and image recognition.  It would make sense to use that, as a starting point.  The combination of running a very small model locally on mobile + LocalAI for a more powerful model when remote PC connectivity is available would be great.

**Comment by davidmigloz** [comment]
[sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx) now has an official Dart client:
- https://pub.dev/packages/sherpa_onnx

**Comment by danemadsen** [comment]
@davidmigloz Sounds great all integrate that for the 1.3 release

**Comment by danemadsen** [comment]
doesnt seem to have out of the box support for flutter TTS yet? only in dart and it needs me to provide my own piper binaries

**Comment by davidmigloz** [comment]
I haven't tried it myself yet, but yes, it's not "out of the box", you have to manage the TTS models yourself.

**Comment by danemadsen** [comment]
@davidmigloz 

Managing the models isnt a problem, its managing the binaries. It doesnt appear they have ffigen set up correctly to compile the required C++ code. 

This would mean i would need to obtain the correct precompiled binaries for Android x86_64 and arm64, Linux, Windows and now MacOS x86_64 and arm64.

Then i would need to ship these precompiled binaries with maid which is something im not willing to do because its against open source and it would cause issues with f-droid.

I am still slowly working on the TTS question but yeah i need it to compile on build

**Comment by davidmigloz** [comment]
ahh indeed, I see what you mean

**Comment by danemadsen** [comment]
babylon_tts is working now
