### ISSUE TITLE
Privacy issue: The app stores data online

### ISSUE THREAD

**Issue by GameOverFlowChart** [Mobile-Artificial-Intelligence/maid#255]
So this is something I knew about for a while because I did reinstall the app a few times.
The thing is Android has apparently a "feature" to save app data on Google drive automagically. I'n the case of maid, this means if you uninstall the app and reinstall it again, you will probably see your old conversation + the profile picture of the bot which Android silently saved in the cloud. 
You can read more about this behavior here:
https://developer.android.com/guide/topics/data/autobackup

I would really like it if maid would opt out from this feature.

**Comment by danemadsen** [comment]
> So this is something I knew about for a while because I did reinstall the app a few times.
> The thing is Android has apparently a "feature" to save app data on Google drive automagically. I'n the case of maid, this means if you uninstall the app and reinstall it again, you will probably see your old conversation + the profile picture of the bot which Android silently saved in the cloud. 
> You can read more about this behavior here:
> https://developer.android.com/guide/topics/data/autobackup
> 
> I would really like it if maid would opt out from this feature.

How do I opt out?

**Comment by GameOverFlowChart** [comment]
> > So this is something I knew about for a while because I did reinstall the app a few times.
> > The thing is Android has apparently a "feature" to save app data on Google drive automagically. I'n the case of maid, this means if you uninstall the app and reinstall it again, you will probably see your old conversation + the profile picture of the bot which Android silently saved in the cloud.
> > You can read more about this behavior here:
> > https://developer.android.com/guide/topics/data/autobackup
> > I would really like it if maid would opt out from this feature.
> 
> How do I opt out?

The link I gave contains a section called "Include and exclude files".
It seems to depend on which Android version you are targeting I would need to read further depending on that, there are a few links for more details which I didn't read for now.

**Comment by GameOverFlowChart** [comment]
Oh seems like you already found it and it was a one liner lol.
