### ISSUE TITLE
Question about allias

### ISSUE THREAD

**Issue by GameOverFlowChart** [Mobile-Artificial-Intelligence/maid#267]
So I didn't write Dart code till now and I'm viewing the code on mobile but I'm pretty sure that "user" is here hardcoded into the String right? It is never replaced by the allias.
`chatml_pfx = ::llama_tokenize(ctx, "\n<|im_start|>user\n", add_bos, true);`
This means that the allias should have no effect at all if you use chatml? (That's not a bad thing)

By looking at the code I did find out that instruct mode ads the "###" and that Chatml is meant to be used without instruct mode, that was probably one reason why I had problems with chatml in the past (I had both active).

So am I right that editing the allias for the user should have no effect at all? Or is the alias string still added somewhere even if instruct mode is disabled?

**Comment by GameOverFlowChart** [comment]
Spoiler alert: from the behavior of the model, I do know that the allias is in fact added so guess it ends up in something like `\n<|im_start|>useruser` or `\n<|im_start|>user user`

I would appreciate if you could hint me at the place in the code where the allias is added.

**Comment by danemadsen** [comment]
Im not really sure what your question is but the user alias is added here:

https://github.com/Mobile-Artificial-Intelligence/maid/blob/main/src/core.cpp#L175-L178

and the assistant alias is added here:

https://github.com/Mobile-Artificial-Intelligence/maid/blob/main/src/core.cpp#L192-L195C10

in core.cpp the alias are refered to as  inp_pfx (user alias) and inp_sfx (assistant alias) this is just how it was in llama.cpp. Hope that helps

**Comment by GameOverFlowChart** [comment]
> Im not really sure what your question is

I'm trying to figure out how the alias is used.

Let me explain it this way I thought that the allias changed the text in this way:
user alias = "Bob"
assistant alias = "assistant"

```
<|im_start|>Bob
Hi
<|im_start|>assistant
Hello, how can I help you?
```

But that seems to not be the case because `<|im_start|>user` is hardcoded.

So what is the app doing instead?
Is it something like this?

```
Bob
<|im_start|>user
Hi
assistant 
<|im_start|>assistant
Hello, how can I help you?
```

Or

```
<|im_start|>userBob
Hi
assistant 
<|im_start|>assistantassitant
Hello, how can I help you?
```

In other words I expected to find something like this in the code
`"<|im_start|>" + useralias;` instead of `"<|im_start|>user"`

I hope this time it was clear.

**Comment by danemadsen** [comment]
The second option is how its added but i can change it pretty easily
