### ISSUE TITLE
Failed to build llama.cpp

### ISSUE THREAD

**Issue by rbrus** [Mobile-Artificial-Intelligence/maid#270]
Hi,

When I run “flutter run” to build and run the project on my Android phone, it fails with the below message. It seems that the submodule llama.cpp is missing a file, or possibly something else. I did some research and found this https://github.com/ggerganov/llama.cpp/issues/3902 however it seems that Maid's project submodule llama.cpp already is updated to the most recent llama.cpp.

Does anybody has any idea what could be the problem and how to fix it? And is able to run the project?

Thanks!

Error:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/dev/maid/android/app/.cxx/Debug/6o266g5k/arm64-v8a'

  C++ build system [build] failed while executing:
      /usr/bin/ninja \
        -C \
        /home/dev/maid/android/app/.cxx/Debug/6o266g5k/arm64-v8a \
        core \
        ggml_shared \
        llama
    from /home/dev/maid/android/app
  ninja: error: '/home/dev/maid/src/llama.cpp/.git/modules/src/llama.cpp/index', needed by '/home/dev/maid/src/llama.cpp/common/build-info.cpp', missing and no known rule to make it

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Running Gradle task 'assembleDebug'...                             19.7s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by morpheus2448** [comment]
Hi did you run `git submodule update --init --recursive`?

**Comment by danemadsen** [comment]
> Hi did you run `git submodule update --init --recursive`?

Yeah probably this.

When cloning you can also do ```git clone --recursive``` to skip that step
