### ISSUE TITLE
Performance and stability issues in post 1.1.8 builds

### ISSUE THREAD

**Issue by Ar57m** [Mobile-Artificial-Intelligence/maid#275]
it's happening with every model I have(shearedllama2.7b, stablelm3b), I'm running the latest app from actions

**Comment by danemadsen** [comment]
yeah im doing alot of work on core.cpp at the moment its likely unstable for the time being.

this build seemed to be more stable on my machine though so maybe give it a try

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7519009453

**Comment by Ar57m** [comment]
> yeah im doing alot of work on core.cpp at the moment its likely unstable for the time being.
> 
> this build seemed to be more stable on my machine though so maybe give it a try
> 
> https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/7519009453

now it seems that with chatml prompt formating is crashing(I'm on Android btw) running stablelm3b based models, with sheared llama3b it generates a little bit and crashes on alpaca prompt format, on chatml it runs a little bit more but at the end of <|im_start|>user it crashes.

**Comment by danemadsen** [comment]
weird, it works fine on linux

**Comment by danemadsen** [comment]
I'm able to get it to prompt with calypso 3B (Alpaca) on my phone but it seems to crash after the second prompt.

**Comment by Ar57m** [comment]
minima-3b-layla-v2.q3_k_m.gguf runs weirdly doesn't stop talking but it hasn't crashed. 
![Screenshot_20240114_103701](https://github.com/Mobile-Artificial-Intelligence/maid/assets/132871733/c90d8db9-7087-41c6-bbbf-04f2b3dd9f24)

**Comment by danemadsen** [comment]
I noticed something similar on desktop with xwin-mlewd-7b, its almost like the format strings arnt being added. Another issue I noticed was sometimes the response would continue the users message.

So I'll definitely have to look into the format logic

**Comment by Ar57m** [comment]
> minima-3b-layla-v2.q3_k_m.gguf runs weirdly doesn't stop talking but it hasn't crashed. On llama.cpp is working normal.

with chatml doesn't crash too but same strange output, and with raw prompt format it kinda leaks the system prompt. 
![Screenshot_20240114_105110](https://github.com/Mobile-Artificial-Intelligence/maid/assets/132871733/f805f893-37a6-432c-83f7-59395fa777c6)

**Comment by danemadsen** [comment]
I think ill move the logic that excludes the user input and system prompt to dart. For some reason I think that's a source of issues and moving it to dart will make it easier to debug

**Comment by danemadsen** [comment]
Haha yeah the only reason its stable now is because i reverted everything back to 1.1.8 and started again lol.

And yeah i can add that pretty easily but all the chat controls are already pretty cluttered so i will probably change them at some point.
