### ISSUE TITLE
Additional stop sequences

### ISSUE THREAD

**Issue by GameOverFlowChart** [Mobile-Artificial-Intelligence/maid#284]
Hello would it be possible to tell llamacpp to add `<|im_end|>` as additional stop sequences if Chatml is selected? The reason is that some models aren't trained for any proper templates,  I can use them with chatml mode but they will end their output with <|im_end|> <|im_start|>.  Using instruct mode instead of chatml also brings some inconveniences because the model doesn't know any of the templates. So it would be a simple solution to enforce the model to stop whenever writes `<|im_end|>`

**Comment by danemadsen** [comment]
possibly, theres a whole lot of issues with core.cpp atm though

**Comment by danemadsen** [comment]
Not sure if this is still an issue but if it is it should probably be transferred to `llama_cpp_dart`

**Comment by GameOverFlowChart** [comment]
Uhm, yeah I will open a issue on llama_cpp_dart once Maid regains all it's functions from 1.1.8 because 1.1.9 isn't usable anyway. Maid would still need a way to expose that functionality I guess.
