### ISSUE TITLE
Make APK releases easy to grab

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Mobile-Artificial-Intelligence/maid#293]
Hi,

The only way currently to use the app on Android is to manually unzip the folder and run it on an Android device.

If possible, please implement the following - 
1. Instead of uploading a zip file, upload the apk directly in releases - this allows apps like Obtainium to update directly via Github. I see that you did follow this until v1.02 . Any reason for not doing so now?
2. Publish to FDroid - Publishing to Fdroid, obviously reaches far greater people and allows them to easily find, install and update the app.

Thanks!

**Comment by danemadsen** [comment]
No real reason for the switch to using zips, it was just because thats how actions serves them.
