### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by ufo147525** [Mobile-Artificial-Intelligence/maid#308]
I hope the software supports multiple languages and has instructions for at least a few of the most common languages.

**Comment by danemadsen** [comment]
Nothing planned as of current. if any localizers want to create some translations they're welcome to do so.

**Comment by ufo147525** [comment]
I just tried the program again, twice, and the result is the same as before, I can see the program occupancy, but I can't make a valid output, I have loaded the model, but it's been three dots loading, and I'm using Chinese input, but the model should support it.
[Default.json](https://github.com/Mobile-Artificial-Intelligence/maid/files/14072350/Default.json)
This should be my config file.
