### ISSUE TITLE
Feature Request: Add MAID as a target for Shared text on Android

### ISSUE THREAD

**Issue by stardomains3** [Mobile-Artificial-Intelligence/maid#321]
In the Android app, have MAID as a target for Shared text. And this text would go in the Prompt text box. I have a Character that just needs a URL. It knows already to then summarize the contents in 7 points. It would be nice to just press share and then select MAID to have the url populate in the prompt text box. 

https://developer.android.com/training/sharing/receive

**Comment by danemadsen** [comment]
Thats an interesting idea, ill look into it. I'm very busy trying to make maid stable for local atm though.
