### ISSUE TITLE
Error loading model file - FilesystemPicker wrong usage on Android

### ISSUE THREAD

**Issue by gawi151** [Mobile-Artificial-Intelligence/maid#331]
Hey I built the app locally on my Android emulator. I wanted to load local model and after clicking on Load GGUF.

The error comes from `FilesystemPicker`:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder(dirty):
You must specify "rootDirectory" or "shortcuts", but not both.
'package:filesystem_picker/src/picker_page.dart':
Failed assertion: line 399 pos 13: '(rootDirectory != null || shortcuts.isNotEmpty) &&
                !(rootDirectory != null && shortcuts.isNotEmpty)'
```

The problem is of course with passing both `rootDirectory` and `shortcuts` at the same time on Android. Probably worth to fix it.

Below video with reproduction steps (app is running in debug mode)
<video src=https://github.com/Mobile-Artificial-Intelligence/maid/assets/2642942/c5113a6c-34c3-4231-b115-6483989513f0 />

**Comment by danemadsen** [comment]
seems like an easy fix, ill look into it
