### ISSUE TITLE
Feature Request: Publish on Google Play

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [Mobile-Artificial-Intelligence/maid#332]
Hello and thanks for this repo,

Can you publish the Android release on Google Play too?

Best,
Orkut

**Comment by danemadsen** [comment]
Yeah i can (and should) but i've hesitated to do so because currently maid isnt very stable and im constantly pushing fixes

**Comment by danemadsen** [comment]
> Yeah i can (and should) but i've hesitated to do so because currently maid isnt very stable and im constantly pushing fixes. It would also neccesitate changing the keys because ive lost the original keyfile for signing the apk's :/

**Comment by orkutmuratyilmaz** [comment]
@danemadsen thanks for your answer:)

**Comment by danemadsen** [comment]
#499
