### ISSUE TITLE
Crashes on Droid all the time

### ISSUE THREAD

**Issue by Manamama** [Mobile-Artificial-Intelligence/maid#334]
I have tried the older version in early January and the newest.

it has never worked, crashes always on offline files, when the reply is to be generated: 
![Screenshot_2024-02-12-17-23-36-46](https://github.com/Mobile-Artificial-Intelligence/maid/assets/78492008/89bf994d-4cdc-4b2b-93be-f2689d962b33)
Quick specs:

> Operating System: Android 11 aarch64      Kernel: 4.14.186+                         Shell: /data/data/com.termux/files/usr/bi Python: 3.11.8                            ------
> 
> Central Processing Unit: MT6785V/CD (8) @ CPU Usage: 1%                             Memory: 3616MiB / 5638MiB                 Disk (/system/priv-app/WapiCertManager/oa Uptime: 3 days, 10 hours, 33 mins         ------                                    Host: realme RMX3085
> 
> 
> Even the tiny: 
> ~/downloads $ ll /storage/emulated/0/Download/LLMs/tinyllama-1.1b-chat-v0.3.Q8_0.gguf                                         -rw-rw---- 1 root everybody 1.1G Jan 29 17:33 /storage/emulated/0/Download/LLMs/tinyllama-1.1b-chat-v0.3.Q8_0.gguf
> 

All these work fine with e.g. python packages:
~/downloads $ llm models                  OpenAI ...
LlamaModel: mistral-7b-instruct-v0.1.Q4_0 LlamaModel: tinyllama-1.1b-chat-v0.3.Q8_0 LlamaModel: tinyllama-1.1b-chat-v0.3.Q5_K_S                                         LlamaModel: orca-mini-3b-gguf2-q4_0       LlamaModel: mistral-7b-openorca.Q4_0      ...

**Comment by danemadsen** [comment]
I know you said the latest but just to clarify this is 1.2.0?

**Comment by danemadsen** [comment]
This should be fixed with #339 now. Ive removed the old 1.2 and will be drafting a new release shortly

**Comment by danemadsen** [comment]
@Manamama I'm closing this as i think its fixed, if its not feel free to reopen it

**Comment by Manamama** [comment]
I have downloaded the update, ver. 1.2.0, used the same mistral 7b instruct v.01  Q4 0 gguf, and similar results. No crash, but no answer either.

The CPU usage creeps up to 2 percent then back to zero , and that is it. 

No logs visible in the GUI, so cannot send anything. 

No logs to send over, alas.
