### ISSUE TITLE
Slow ai model respond

### ISSUE THREAD

**Issue by vialonitasuhardiman** [Mobile-Artificial-Intelligence/maid#335]
When integrating AI models, I have noticed that they typically take a long time to respond, except when I simply greet them with "hello," to which they promptly reply with the same word. Despite having strong specifications (namely, 8 GB of RAM and a Snapdragon 870 processor), running models with 500 million parameters remains a sluggish process.

**Comment by danemadsen** [comment]
yeah its an issue with llama_cpp_dart, not something i can fix in maid for now. You can use 1.1.8 and below for better performance if you need.

**Comment by vialonitasuhardiman** [comment]
Ok thanks
