### ISSUE TITLE
Generation not working for specific models on version 1.2.0+

### ISSUE THREAD

**Issue by RookieIndieDev** [Mobile-Artificial-Intelligence/maid#338]
Generates this only as the output when using the model tinyllama-2-1b-miniguanaco.Q3_K_L

![Screenshot_20240215-110002.png](https://github.com/Mobile-Artificial-Intelligence/maid/assets/5702107/c714d8e6-98a8-4f71-aaf1-48d03222de1c)

**Comment by RookieIndieDev** [comment]
Link to the model here: [HF link](https://huggingface.co/TheBloke/Tinyllama-2-1b-miniguanaco-GGUF)

**Comment by danemadsen** [comment]
Ok #339 should fix this. Still getting some artifacting but at-least you can have an output now

**Comment by RookieIndieDev** [comment]
Still having the same issue.

**Comment by danemadsen** [comment]
> Still having the same issue.

Any change in the output at all?

**Comment by RookieIndieDev** [comment]
> > Still having the same issue.
> 
> Any change in the output at all?

No change.

**Comment by Eidenz** [comment]
Got the same problem but with remote Ollama.

**Comment by danemadsen** [comment]
> Generates this only as the output when using the model tinyllama-2-1b-miniguanaco.Q3_K_L
That model is super weird, i dont get any output even on desktop even when other models work fine

**Comment by RookieIndieDev** [comment]
> > Generates this only as the output when using the model tinyllama-2-1b-miniguanaco.Q3_K_L
> 
> That model is super weird, i dont get any output even on desktop even when other models work fine
> 

This model was able to output stuff in the previous versions though.

**Comment by danemadsen** [comment]
> > > Generates this only as the output when using the model tinyllama-2-1b-miniguanaco.Q3_K_L
> > 
> > 
> > That model is super weird, i dont get any output even on desktop even when other models work fine
> 
> This model was able to output stuff in the previous versions though.

Ok well this is an issue with llama_cpp_dart so ill close it here and move it over there

**Comment by danemadsen** [comment]
Transferred https://github.com/netdur/llama_cpp_dart/issues/26

**Comment by RookieIndieDev** [comment]
Not sure if generation is very slow or it simply isn't working but the loading indicator is shown for a long amount of time when tried with tinyllama-1.1b-1t-openorca.Q4_0. Maybe I should start a new issue?

**Comment by danemadsen** [comment]
@RookieIndieDev ok give https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/8127833802 a go and tell me how you go. 

Its a new implementation so its not ready for a release yet and i still need to work on removing the user prompt from the output but you should be able to gauge the performance

**Comment by RookieIndieDev** [comment]
> @RookieIndieDev ok give https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/8127833802 a go and tell me how you go. 
> 
> Its a new implementation so its not ready for a release yet and i still need to work on removing the user prompt from the output but you should be able to gauge the performance

Says the APK build failed?

**Comment by danemadsen** [comment]
ahh yeah sorry gimme a sec

**Comment by danemadsen** [comment]
@RookieIndieDev ok try this one

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/8128111631

**Comment by RookieIndieDev** [comment]
Tried both on Windows and Android. Android crashes immediately after pressing the send button, ON Windows it does nothing, just stays there with the loading button without any CPU usage or more memory being allocated when viewed in the task manager

**Comment by danemadsen** [comment]
> Tried both on Windows and Android. Android crashes immediately after pressing the send button, On Windows it does nothing, just stays there with the loading button without any CPU usage or more memory being allocated when viewed in the task manager

Ok ive only tested on linux so ill text windows and android later this week

**Comment by RookieIndieDev** [comment]
Updated to 1.2.2 release (setting says 1.2.1 though), tried generating with the [TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF), had it open for more than 10 mins now, it still shows the loading indicator and no output so far.

**Comment by danemadsen** [comment]
> Updated to 1.2.2 release (setting says 1.2.1 though), tried generating with the [TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF), had it open for more than 10 mins now, it still shows the loading indicator and no output so far.

I republished, windows should work now

**Comment by RookieIndieDev** [comment]
Haven't tried on Windows yet but on android it's still the case.

**Comment by RookieIndieDev** [comment]
Crashes on Windows immediately after clicking the arrow button. Tried both TinyLlama and capybarahermes-2.5-mistral-7b.Q4_K_M. Found this in the Event Viewer log: 
`Faulting application name: maid.exe, version: 1.2.2.0, time stamp: 0x65f38908
Faulting module name: llama.dll, version: 0.0.0.0, time stamp: 0x65f388c3
Exception code: 0xc0000005
Fault offset: 0x0000000000078bae
Faulting process id: 0xef8
Faulting application start time: 0x01da76e8657afd7d
Faulting application path: \maid-windows\maid.exe
Faulting module path: \maid-windows\llama.dll
Report Id: 27a306e9-3c4b-431c-9d36-afc1f890b396
Faulting package full name: 
Faulting package-relative application ID: `

on Windows 10
