### ISSUE TITLE
Possibility of using Mamba SSM

### ISSUE THREAD

**Issue by RookieIndieDev** [Mobile-Artificial-Intelligence/maid#390]
Mamba SSM architecture has some improvements over the standard transformer based LLMs it seems. [Mamba Paper](https://arxiv.org/abs/2312.00752). There are people working on implementations with llama.cpp, mentioned in [this](https://github.com/ggerganov/llama.cpp/issues/4353) GitHub thread towards the end

**Comment by danemadsen** [comment]
Will be added once its in llama cpp

**Comment by RookieIndieDev** [comment]
Looks like Mamba support has been merged master branch of llama.cpp [PR Link](https://github.com/ggerganov/llama.cpp/pull/5328)

**Comment by danemadsen** [comment]
updated llama cpp and merged
