### ISSUE TITLE
Can't get Ollama to work on Android

### ISSUE THREAD

**Issue by tusharhero** [Mobile-Artificial-Intelligence/maid#391]
I haven't tested the other platforms, but I am not able to use ollama which is running on my VPS. Looking through you code you seem to be doing something weird to automatically find the locally running Ollama? I am not sure though.

**Comment by tusharhero** [comment]
https://github.com/Mobile-Artificial-Intelligence/maid/blob/e7a29ef98c01d4f7b96bf39eafce7567ea188e0b/lib/static/generation_manager.dart#L326-L354

Why not just ask the user for the address?

**Comment by danemadsen** [comment]
You can set the address manually if you know the address but ive just set it to find the local address automatically as in general thats where most people will be hosting it.

**Comment by tusharhero** [comment]
When I select ollama, I get no option to choose the address.
![Screenshot_20240302-194317_Maid](https://github.com/Mobile-Artificial-Intelligence/maid/assets/54012021/d0c7ed58-2ace-4563-b04b-47062293e6a2)
