### ISSUE TITLE
Ollama Remote Not Configurable through GUI - Windows - 1.2.1

### ISSUE THREAD

**Issue by Timman6866** [Mobile-Artificial-Intelligence/maid#429]
Hello!

I have found an issue where the Ollama API type cannot be configured with a URL in the GUI in the windows client.  Selecting 'Ollama' does not present a dropdown for URL. If another API is selected the URL field appears. Saving the configuration of another API type and then manually setting the API type to "api_type: 3" seems to overcome the GUI limitation.

**Comment by danemadsen** [comment]
is this from an actions build or a release build?
