### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by BurrHM** [Mobile-Artificial-Intelligence/maid#465]
That would be great. See [here](https://f-droid.org/en/docs/Inclusion_Policy/)

**Comment by danemadsen** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14848

**Comment by danemadsen** [comment]
Ok Maid has been successfully added to F-Droids repo. In the next 3-7 days it will be built and made available in the app. Once this is possible ill add a link to the readme.
