### ISSUE TITLE
Pixel 5 Android does nothing, constant loading

### ISSUE THREAD

**Issue by knuxyl** [Mobile-Artificial-Intelligence/maid#470]
I am using llama 2 gguf and it says it loaded successfully but when prompted it does nothing, just a constant 3 dot animation like it's loading. Eventually it will just stop the animation and show no output but with the option to refresh the response again.
Pixel 5 is 8 core Snapdragon 765G with 8GB ram (app says 7 GB ram) and Adreno 620. I'm running Lineageos 20 Android 13
App settings log has this, i ommitted full path to gguf

> Storage - Permission granted
> loading model from File: 'llama2.gguf'
> Initializing LLM
> Prompting with llamacpp
> Model init in 22.724575 seconds
> Context init in 0.610512 seconds
> Prompt stopped in 777.150114 seconds
> n_ctx: 512
> {name: llama.gguf, uri: /path/to/llama.gguf, token: , randomSeed: true, useDefault: false, penalizeNewline: true, seed: 0, nKeep: 48, nPredict: 512, topK: 40, topP: 0.95, minP: 0.1, tfsZ: 1.0, typicalP: 1.0, temperature: 0.8, penaltyLastN: 64, penaltyRepeat: 1.1, penaltyFreq: 0.0, mirostat: 0, mirostatTau: 5.0, mirostatEta: 0.1, nCtx: 512, nBatch: 512, nThread: 8, promptFormat: 2}

I tried chaning to ChatML but eventually it crashed. Heres what it gave me

> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> LineageOS Version: '20.0-20240214-microG-redfin'
> Build fingerprint: 'google/redfin/redfin:13/TQ3A.230901.001/10750268:user/release-keys'
> Revision: 'MP1.0'
> ABI: 'arm64'
> Timestamp: 2024-04-05 22:35:39.185243274-0500
> Process uptime: 1874s
> Cmdline: com.danemadsen.maid
> pid: 31245, tid: 3581, name: DartWorker  >>> com.danemadsen.maid <<<
> uid: 10237
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
> Cause: null pointer dereference
>     x0  b4000070252c6c00  x1  0000000000000000  x2  000000000001f400  x3  b4000070252c6c00
>     x4  000000000001f400  x5  b4000070252e6000  x6  6e6b1f63686b6075  x7  7f7f7f7f7f7f7f7f
>     x8  00000000000000b4  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
>     x12 00000000252e6000  x13 65757274203d2120  x14 0000000000000000  x15 00000072d733367a
>     x16 0000007024de5f70  x17 00000072d735b810  x18 0000006f6f3a4000  x19 b4000070252e6000
>     x20 0000006fc2f69000  x21 000000000001f400  x22 b400007108fc3150  x23 0000000000000000
>     x24 0000000000007d00  x25 0000000000000000  x26 0000000000000000  x27 0000006fc2f667b8
>     x28 b4000070252c6c00  x29 0000006fc2f666f0
>     lr  0000007024dd84a0  sp  0000006fc2f66680  pc  00000072d735b788  pst 0000000020001000
> backtrace:
>       #00 pc 000000000004d788  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+232) (BuildId: f73b4091a9c819a21763f5bf11b53c2b)
>       #01 pc 000000000004c49c  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libmaid.so (offset 0x13d5000) (llama_sampling_prepare(llama_sampling_context*, llama_context*, llama_context*, int, bool, std::__ndk1::vector<float, std::__ndk1::allocator<float> >*)+224) (BuildId: bf02d716a2a0bdc39def5c31cf6d105a05053890)
>       #02 pc 000000000004bfc8  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libmaid.so (offset 0x13d5000) (BuildId: bf02d716a2a0bdc39def5c31cf6d105a05053890)
>       #03 pc 0000000000027a7c  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libmaid.so (offset 0x13d5000) (maid_llm_prompt+1216) (BuildId: bf02d716a2a0bdc39def5c31cf6d105a05053890)
>       #04 pc 0000000000281598  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #05 pc 0000000000631ccc  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #06 pc 0000000000631bb0  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #07 pc 0000000000631aa8  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #08 pc 00000000006319c8  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #09 pc 00000000006f0f0c  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #10 pc 000000000029b910  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #11 pc 00000000006f0f0c  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #12 pc 00000000002994fc  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #13 pc 0000000000283d2c  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk (offset 0x52000) (BuildId: b866ace1305b963fcfd3110f3b170cea)
>       #14 pc 000000000083bdf4  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libflutter.so (offset 0x753000) (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
>       #15 pc 0000000000847784  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libflutter.so (offset 0x753000) (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
>       #16 pc 000000000084c9b4  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libflutter.so (offset 0x753000) (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
>       #17 pc 000000000084c778  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libflutter.so (offset 0x753000) (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
>       #18 pc 00000000008e16c0  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libflutter.so (offset 0x753000) (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
>       #19 pc 00000000008a6d6c  /data/app/~~jTuJc5S3Du3ps-cT5pdnUg==/com.danemadsen.maid-tJzo19sfbkpnEDC4GEbaXQ==/base.apk!libflutter.so (offset 0x753000) (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
>       #20 pc 00000000000b6380  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: f73b4091a9c819a21763f5bf11b53c2b)
>       #21 pc 00000000000530a8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: f73b4091a9c819a21763f5bf11b53c2b)

**Comment by danemadsen** [comment]
Not sure why its crashing, Ive added more logs in the latest actions build so maybe run that and see if there's a different log. Its likely due to limited ram though.
