### ISSUE TITLE
OS X release is missing

### ISSUE THREAD

**Issue by rodion-m** [Mobile-Artificial-Intelligence/maid#473]
I haven't found a release for OS X (MacOS) in the releases page. Should I compile it by myself?

**Comment by danemadsen** [comment]
You can try, The UI is most likely broken and llama.cpp certainly wont work. I havnt supported MacOS because i dont have a Mac or Iphone to test and develop it

**Comment by DoubleMalt** [comment]
@danemadsen I'll give it a try and might be able and willing to try to get it to work.

**Comment by danemadsen** [comment]
@DoubleMalt OS X is working now, you can download a build from actions but you'll have to disable the gatekeeper to run it. Im just sorting out a signing key now so you wont have to do this in the future.

MacOS support will be in the 1.2.9 release which should release soon.
