### ISSUE TITLE
I can't chat

### ISSUE THREAD

**Issue by akrram0** [Mobile-Artificial-Intelligence/maid#504]
Nice app but I didn't make it to respond like I've been like 1 min fitghing switching between them the app is not responsive like tapping pause but doesn't seem to work here is error file 
[maidtxt.txt](https://github.com/Mobile-Artificial-Intelligence/maid/files/15054796/maidtxt.txt)
Edit: here is a video

**Comment by akrram0** [comment]
https://github.com/Mobile-Artificial-Intelligence/maid/assets/140515513/2f5eb09a-f60b-47fb-8b08-bd2befffd35a

**Comment by saddlerto** [comment]
```
Error initializing model: Exception: Model URI is empty
{}
```
You have to download a [GGUF model from huggingface](https://huggingface.co/models?library=gguf&sort=trending) onto your device and load it in if you use the `LlamaCPP` option.

```
Prompting with openAI
```

Did you put in a valid OpenAI API key when you tried this option?

**Comment by danemadsen** [comment]
Yeah you can't use it out of the box, you need a model to load into it or have an api key for one of the APIs.

I'll need to add a popup to explain that better though.

**Comment by saddlerto** [comment]
> > ```
> > Error initializing model: Exception: Model URI is empty
> > {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You have to download a [GGUF model from huggingface](https://huggingface.co/models?library=gguf&sort=trending) onto your device and load it in if you use the `LlamaCPP` option.
> > ```
> > Prompting with openAI
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did you put in a valid OpenAI API key when you tried this option?
> 
> Hey thank you, but when I enter the link i didn't manage to download the API key can you show how to do that?

If your device is powerful enough to run a small local model, then you'll need to download one from the huggingface link, then go the the settings and load the model

If you want to use the OpenAI API, then you need to create an OpenAI account, then follow the instructions [on this page to get your API key](https://help.openai.com/en/articles/4936850-where-do-i-find-my-openai-api-key). This is not a free option, will require you to put in credit card information.

There are other ways to use an OpenAI-compatible API, but that is beyond the scope of anything I can talk about here.
