### ISSUE TITLE
model url dosnt update when loading model.

### ISSUE THREAD

**Issue by nntb** [Mobile-Artificial-Intelligence/maid#506]
so added a gguf model that worked before... and 
clear cache: 
Character Initialised
Session Initialised
Character loaded from MCF
Character created with name: Maid
Character reset
LLM PARAMETERS> 
Error Initilizing model exeption model URI is empty.

**Comment by nntb** [comment]
i confirmed the models work on lm studio in windows. 

![Screenshot_20240423_095614_Files](https://github.com/Mobile-Artificial-Intelligence/maid/assets/5661028/9f030493-514c-4f55-ba2e-bb67a9e188fd)

**Comment by nntb** [comment]
figured it out i am not waiting long enough. there is no indication on the screen after selecting a model that its loading. no ... no spinner nothing... so i didnt realize it was not yet loaded.

**Comment by danemadsen** [comment]
Yeah ill add a spinner at some point
