### ISSUE TITLE
OpenAI API Url field doesn't save

### ISSUE THREAD

**Issue by h3ndrik** [Mobile-Artificial-Intelligence/maid#513]
If I switch chats or pause the App or do anything the URL field always reverts to the default.

Also the text input field seems broken on my device, the cursor always jumps to the end making it next to impossible to edit text in the middle.

(And there isn't any error message, the conversation just shows that it's processing indefinitely, despite the request probably having failed.)

Android 13 (F-Droid version of Maid)
I'm trying to connect it to [KoboldCPP](https://github.com/LostRuins/koboldcpp)'s OpenAI compatible endpoint, which works for one message until I run into this issue.

**Comment by henk717** [comment]
Having the same issue, it doesnt appear to get a model list? Test URl is here : https://koboldai-koboldcpp-tiefighter.hf.space/v1

**Comment by danemadsen** [comment]
I believe this is fixed now so I'm closing. If not let me know and I'll reopen.

**Comment by RealJohnGalt** [comment]
I can recreate this on current HEAD and 1.2.7 android builds. I figured saving the url field was unsupported until seeing this issue.
