### ISSUE TITLE
Doesn't work on budget phone? But should...

### ISSUE THREAD

**Issue by mlsterpr0** [Mobile-Artificial-Intelligence/maid#519]
I know my device is old and slow (poco x3), but! I tried another app from googleplay, and it can run gguf models up to 2-4B parameters pretty fast on my phone, very usable(like 3-5t/s). But this app not only takes lots of time, but also not giving me any output. Tried calypso 3b, phi-2, phi-3 and changing settings. Phone gets hot, but no output after waiting like 3-5minutes. Phone has 6+2gb ram.

**Comment by danemadsen** [comment]
What's the app on google play?

**Comment by mlsterpr0** [comment]
> What's the app on google play?

LM Playground. It's super basic now, without any settings. Only several models available. But at least using it, i know that my phone can run phi-2 pretty fast.

**Comment by danemadsen** [comment]
I tested LM Playground, it is indeed faster but it also doesnt seem to process any sort of preprompt prior to generation (like maid does). I should add some form of ability to disable the preprompt (character)
