### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by NielSync** [Mobile-Artificial-Intelligence/maid#523]
The Maid app icon should adapt to the Android color theme and icon shape.
Currently the app icon is white padded around it and looks small.
![Img_2024_04_28_06_30_17~2.jpeg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/20804647/dfd84327-51c4-40d5-ba79-16cbf88b0882)

**Comment by danemadsen** [comment]
Ahh yeah I've noticed it does the same thing on the tablet I'm using. Any ideas how to fix it?

**Comment by vijaykarthiktk** [comment]
Please Assign it to me.

**Comment by danemadsen** [comment]
> Please Assign it to me.

Go crazy

**Comment by danemadsen** [comment]
@vijaykarthiktk I noticed the icon images you submitted are missing the maids headpiece from the logo. I'd love it if you could fix this up and resubmit a PR. Else I will fix it later.

**Comment by vijaykarthiktk** [comment]
Oops! You're totally right, the maid's missing her crown in the icons   Fixing it now and will resubmit a PR ASAP.

**Comment by vijaykarthiktk** [comment]
Fixed the missing crown on the maid in the icons. Just submitted a PR. Please review and merge.
