### ISSUE TITLE
ollama not using api key

### ISSUE THREAD

**Issue by theoden8** [Mobile-Artificial-Intelligence/maid#530]
Good afternoon,

First of all, thank you for a great project. It's by far the only F-Droid app that allows me to use self-hosted LLMs.

It seems that authentication with ollama using api key is not implemented at all, making the app recieve 403 when connecting to my authenticated endpoint.

I believe the parent class of ollama has token, while the child does not use it:

https://github.com/Mobile-Artificial-Intelligence/maid/blob/main/lib/classes/ollama_model.dart (search for "header")

Adding it to the header could be done like this:

https://github.com/davidmigloz/langchain_dart/issues/399

**Comment by danemadsen** [comment]
Ahh yes I was aware of this but I forgot to fix it as I didn't think anyone was actually using ollama with a key. Its an easy fix.

**Comment by theoden8** [comment]
I wanted to use ollama on mobile, so ssh -L isn't an option, but running without auth is a bit too much.

I'm using https://github.com/ParisNeo/ollama_proxy_server, which uses bearer token for api key. Not sure if it's compatible but openai client seems to get through

**Comment by danemadsen** [comment]
I'm using langchain dart for ollama so I'll have to look if auth is an option for that.

**Comment by davidmigloz** [comment]
When instantiating `ChatOllama`:
https://github.com/Mobile-Artificial-Intelligence/maid/blob/2479541ed21c168bd24806d753b10d3b18626791/lib/classes/ollama_model.dart#L191-L197

You can add custom headers using the `headers` field. E.g:
```dart
final chat = ChatOllama(
  baseUrl: '$uri/api',
  headers: { 'api-key': 'YOUR_API_KEY' },
  defaultOptions: ChatOllamaOptions(
    model: name,
    seed: seed
  ),
);
```

**Comment by danemadsen** [comment]
OK this should work

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/8966774761

Can't test it myself because I'm out of town and I don't have my laptop

**Comment by theoden8** [comment]
The authentication seems to be missing from the headers. It's not present. I've installed the version from the link you've provided.

**Comment by danemadsen** [comment]
@theoden8 Ok try this one

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/9043686207

**Comment by theoden8** [comment]
Sorry for the delay, had trouble downloading the APK due to some DNS resolution thing.

```
127.0.0.1 - - [12/May/2024 12:12:45] "GET /api/tags HTTP/1.0" - -
User is not authorized
127.0.0.1 - - [12/May/2024 12:12:45] "GET /api/tags HTTP/1.0" 403 -
127.0.0.1 - - [12/May/2024 12:13:58] "GET /api/tags HTTP/1.0" - -
User is not authorized
127.0.0.1 - - [12/May/2024 12:13:58] "GET /api/tags HTTP/1.0" 403 -
```

**Comment by danemadsen** [comment]
So its still not authd? Dam I really don't know what's going on then.

With regards,
Dane Madsen
________________________________

**Comment by theoden8** [comment]
Let me try and print what's being sent and what's being received.

**Comment by theoden8** [comment]
So, here's the problem.

1. https://github.com/Mobile-Artificial-Intelligence/maid/blob/main/lib/classes/ollama_model.dart#L140 doesn't have authorization
2. https://github.com/Mobile-Artificial-Intelligence/maid/blob/main/lib/classes/ollama_model.dart#L239 doesn't have authorization
3. wait for it... https://stackoverflow.com/questions/66579219/flutter-http-request-header-key-lowercase

The header keys are converted to lowercase.

**Comment by theoden8** [comment]
Another problem is that "Bearer: " is incorrect as per https://datatracker.ietf.org/doc/html/rfc6750.

**Comment by bartolli** [comment]
Check out my repo, it’s a simple, secure way to manage API key authentication for your Ollama apps with a Caddy server.

https://github.com/bartolli/ollama-bearer-auth-caddy
