### ISSUE TITLE
APP process only runs on CPU7 on Android device

### ISSUE THREAD

**Issue by TwinbornPlate75** [Mobile-Artificial-Intelligence/maid#560]
Not sure if this happens on every android device.
Information about my device
   System: Xiaomi Hyper OS (Android 14)
   Processor: Snapdragon 855
   Ram: 12GB
![Screenshot_2024-05-17-08-33-23-665_com danemadsen maid-edit](https://github.com/Mobile-Artificial-Intelligence/maid/assets/42514046/63c1b53c-8553-440b-a176-fc5b6d4b7f0d)

**Comment by danemadsen** [comment]
Not really sure if its an issue with the app or something device specific but all cores are maxxed out on my device
![Screenshot_2024-05-17-11-03-22-37_f491d42f48f7e59ed03e7bce3f3fe7a5.jpg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/11537699/6f3a90da-d163-40f8-8be1-3083d55f7312)

**Comment by danemadsen** [comment]
all good, let me know if you find anything out that i need to fix

**Comment by TwinbornPlate75** [comment]
> all good, let me know if you find anything out that i need to fix

I reverted changes to kernel, but app still only runs on CPU7, strange problem

**Comment by TwinbornPlate75** [comment]
> all good, let me know if you find anything out that i need to fix

Problem solved, it's caused by a module. I'm sorry to bother you for my mistake

**Comment by danemadsen** [comment]
> > all good, let me know if you find anything out that i need to fix
> 
> Problem solved, it's caused by a module. I'm sorry to bother you for my mistake

All good, no bother
