### ISSUE TITLE
What things incomplete for iOS?

### ISSUE THREAD

**Issue by cjl84914** [Mobile-Artificial-Intelligence/maid#561]
I have success to build Macos.
What things incomplete for iOS?

**Comment by danemadsen** [comment]
I'm fairly sure macos and iOS should build OK (I have no way of testing). The issue is that maid_llm isn't setup to build the C++ code for those platforms so llama.cpp won't work on either platform.

**Comment by cjl84914** [comment]
ok, thank you.
