### ISSUE TITLE
Feature Request: Custom Openai endpoints

### ISSUE THREAD

**Issue by Detla7t** [Mobile-Artificial-Intelligence/maid#564]
Hi I recently downloaded your app and noticed that you do support openai what I was hoping is that you could open up access to the port options so that people can use openai compatible endpoints such as LM Studio, Oobabooga and others I think you would only need to give access so that the user can set a custom port unless there is a way that I didn't see. thanks and hope this isn't too much trouble.

**Comment by danemadsen** [comment]
Ahhh, ok i think that's expected behavior.  I cant make it work without the /v1 because that's all handled in langchain dart which is upstream from maid.

**Comment by davidmigloz** [comment]
Not all providers that offer an OpenAI-compatible API include `/v1`, so I would keep it as part of the base URL.
E.g. Azure uses `https://{YOUR_RESOURCE_NAME}.openai.azure.com/openai/deployments/{YOUR_DEPLOYMENT_NAME}/`
