### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ggiidd** [Mobile-Artificial-Intelligence/maid#567]
I hope the author will add, a button to clear the chat log. Or New Conversation retains the model, it's that New Chat, when switching the local model is gone, but in fact it's still there, only it can't be used in the new conversation, the result is that the application will get bigger and bigger, because the new conversation can't use the model that has already been added, so you have to add it again, but the previous model is still there, so it will get bigger and bigger, and it can't be cleared, unless you clear the cache, but then.It's like formatting all over again, all the information is gone, I hope it can be solved. I hope this can be solved. I hope this can be solved. Also, when you clear the cache, can you not clear the character cards and model data? It's really a bit of a pain in the ass, and I hope it's just in that see, I love your app!

**Comment by amanhigh** [comment]
I feel this is genuine problem. Switching to new chat always reverts back to lama.cpp even though openapi is configured.
