### ISSUE TITLE
App gets soft locked when there's issues reaching API server

### ISSUE THREAD

**Issue by PylotLight** [Mobile-Artificial-Intelligence/maid#568]
I've been using Maid as a frontend for my own custom AI server, but if you happen to submit a call that fails or can't reach the server the whole app gets frozen and the red stop button doesn't work/do anything. 

Ideally the app times out quickly and returns an error.

**Comment by danemadsen** [comment]
Is this with Ollama i assume?

**Comment by PylotLight** [comment]
> Is this with Ollama i assume? The red stop button should only be present for llama.cpp

Nope openAI

**Comment by danemadsen** [comment]
This bug may be fixed, can you check 1.2.9 and report back if its still present?

**Comment by PylotLight** [comment]
After getting the update in fdroid and testing it, it's still the same issue with the loading screen being stuck and not being able to cancel without closing the app.
not planned or not, this is still an issue.

**Comment by PylotLight** [comment]
1. Configure an inaccessible openai custom local endpoint
2. Send prompt
3. App locks up


![Screenshot_20240709_214151.jpg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/7006124/ac5cc1df-dbe6-4c8b-8b05-d35e27f6d882)

**Comment by danemadsen** [comment]
@PylotLight I cant reproduce it. I followed your steps and it just gets caught by the missing requirements check as not having a model selected?

**Comment by danemadsen** [comment]
I added a fix which should now prevent you from sending a prompt to an invalid API

You can try it here:
https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/9868649017

**Comment by PylotLight** [comment]
So essentially requiring you to select a model which auto forgets/checks if that model is available right? 
If that's the case then yes that's working currently. 

Ideally it would always remember that model is selected so I don't have to select the model everytime I open the app but otherwise we should be good for now.
