### ISSUE TITLE
After the new version all local models are unavailable, what ever you ask it will talk about a different topic and is completely uncommunicative.

### ISSUE THREAD

**Issue by ggiidd** [Mobile-Artificial-Intelligence/maid#570]
![Screenshot_2024_0531_171959.jpg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/116434731/1a67f9e3-85ff-4b8d-9050-ef656de5311c)

**Comment by danemadsen** [comment]
Ill look into it. It must be an issue with llama_apply_chat_template

**Comment by danemadsen** [comment]
@ggiidd I dug into the code and it seems the gibberish is occuring because if nPredict is more than or equal to nCtx all the data in the preprompt gets dropped. I can fix this in the next release but in the meantime you should make sure nCtx is set to a value much higher than nPredict
