### ISSUE TITLE
Only the latest character gets saved

### ISSUE THREAD

**Issue by PinkSerenity** [Mobile-Artificial-Intelligence/maid#571]
OS: Android 14 (GSI)

How to reproduce:
- open the character overview by clicking on "Browse"
- repeatedly click on the + icon to add characters
- edit one and give them a name
- save and return to the main screen
- open the character overview again

Expected result:
You can see all the characters.

Actual result:
You only see the one you edited.

Furthermore:
- create another character
- edit them and give them a name
- save and return to the main screen
- access the character overview again

The first character is now gone as well.

**Comment by danemadsen** [comment]
Hmm I'm not sure I'm concerned about it dropping empty / unedited characters. But if its dropping characters you have edited that's something ill have to fix

**Comment by danemadsen** [comment]
seems to have been fixed in the process of making the desktop ui
