### ISSUE TITLE
Open ai API link changes on restart

### ISSUE THREAD

**Issue by jimd-den** [Mobile-Artificial-Intelligence/maid#572]
When using other API the link switches back to openai

**Comment by danemadsen** [comment]
So to clarify is this when closing then restarting the app?

**Comment by jimd-den** [comment]
actually when you select lama.cpp or anything else, it'll  reset the link, when you select a maid option. and yest just closing, everytime you close

**Comment by danemadsen** [comment]
I cant reproduce this on the latest build?

**Comment by jimd-den** [comment]
> I cant reproduce this on the latest build?

You are right, should've updated
