### ISSUE TITLE
Failed to load dynamic library 'maid.dll'.

### ISSUE THREAD

**Issue by cjl84914** [Mobile-Artificial-Intelligence/maid#574]
Good morning.
I try maid-windows of LlamaCpp func.
I have loaded a llama-2 model, log showed Failed to load dynamic library 'maid.dll'.
![R04HQS02VH$@9LYF81U4M6X](https://github.com/Mobile-Artificial-Intelligence/maid/assets/4083885/c396b814-2424-46c4-b412-4f1124dd2205)

**Comment by danemadsen** [comment]
I cant reproduce your error on windows? Are you moving the exe away from where it was extract? What version are you using?

**Comment by cjl84914** [comment]
I use this version:
https://github.com/Mobile-Artificial-Intelligence/maid/releases/download/1.2.8/maid-windows.zip
Operation steps:

1. unzip 
2. double click maid.exe
3.  click load GUFF button select llama-2-7b-chat.Q2_K.gguf and Model Successful Loaded.
model has download form:
https://huggingface.co/monal04/llama-2-7b-chat.Q4_0.gguf-GGML/tree/main
4. return and send "hello" prompt, wait moment no response.
5. log show:
![image](https://github.com/Mobile-Artificial-Intelligence/maid/assets/4083885/07cca514-9b3e-48ba-a709-980912660079)

my OS is windows10 x64 22H2.

**Comment by danemadsen** [comment]
> I use this version:
> https://github.com/Mobile-Artificial-Intelligence/maid/releases/download/1.2.8/maid-windows.zip
> Operation steps:
> 
> 1. unzip 
> 2. double click maid.exe
> 3.  click load GUFF button select llama-2-7b-chat.Q2_K.gguf and Model Successful Loaded.
> model has download from:
> https://huggingface.co/monal04/llama-2-7b-chat.Q4_0.gguf-GGML/blob/main/llama-2-7b-chat.Q2_K.gguf
> 4. return and send "hello" prompt, wait moment no response.
> 5. log show:
> ![image](https://github.com/Mobile-Artificial-Intelligence/maid/assets/4083885/07cca514-9b3e-48ba-a709-980912660079)
> 
> my OS is windows10 x64 22H2.
> 
> 

Dam, OK is there any previous versions that do work for you?

**Comment by cjl84914** [comment]
I tested 1.2.6 that same error.

**Comment by danemadsen** [comment]
@cjl84914 what was the issue?

**Comment by liudonghua123** [comment]
I have the similar issue, the error log is

```
Character loaded from MCF
{}
Character loaded from MCF
Character reset
File selected: C:\Users\Liu.D.H\qwen2.5-0.5b-instruct-q5_k_m.gguf
Loading model from File: 'C:\Users\Liu.D.H\qwen2.5-0.5b-instruct-q5_k_m.gguf'
Prompting with llamacpp
Initializing LLM
Invalid argument(s): Failed to load dynamic library 'maid.dll': The specified module could not be found.
 (error code: 126)
```

![image](https://github.com/user-attachments/assets/81270c6e-9593-40cf-972b-09ac6247b25e)

![image](https://github.com/user-attachments/assets/9ca24c2a-5f96-4600-a493-7fcfdc603ffc)
