### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by Phoenix1025** [Mobile-Artificial-Intelligence/maid#578]
Can anyone leave a guide to use/setup this app on android for beginners and non technical experts like me.  Its even hard to get a model from the huggingface website using cellphone. So pls if anyone has time to put a step by step guide for newbies, it would be great. Thanks!

**Comment by predbrad** [comment]
seems like a dupe of https://github.com/Mobile-Artificial-Intelligence/maid/issues/562

**Comment by danemadsen** [comment]
dupe
