### ISSUE TITLE
Add functionality to download select models from hugginface directly

### ISSUE THREAD

**Issue by danemadsen** [Mobile-Artificial-Intelligence/maid#579]

**Comment by Phoenix1025** [comment]
Yes that would be great.

**Comment by predbrad** [comment]
I think this would be huge. I'd just copy the functionality of LM Playground, which works well out of the box with a few select models https://play.google.com/store/apps/details?id=com.druk.lmplayground

This will also remove the need for a beginners guide and advanced docs as mentioned in these issues:

- https://github.com/Mobile-Artificial-Intelligence/maid/issues/562
- https://github.com/Mobile-Artificial-Intelligence/maid/issues/578
