### ISSUE TITLE
qwen 2 model outputs gibberish.

### ISSUE THREAD

**Issue by chaihahaha** [Mobile-Artificial-Intelligence/maid#581]
![Screenshot_20240704_202921.jpg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/24356676/35b7c895-8251-4b8b-85b8-8e5a5eee3103)

qwen 2 1.5b and 7b quantized with Q6k or Q4km (by bartowski on huggingface) are not working on maid. The output is normal on PC with llama.cpp, but is weird on Maid App.

**Comment by danemadsen** [comment]
You might want to try this again now that ive published 1.2.9

**Comment by chaihahaha** [comment]
After upgrading to 1.2.9, qwen2 is working seamlessly and much faster, thank you very much for you awesome work！

**Comment by danemadsen** [comment]
@chaihahaha cool beans! :)
