### ISSUE TITLE
Output problem.

### ISSUE THREAD

**Issue by mlsterpr0** [Mobile-Artificial-Intelligence/maid#584]
I hope someone will help me solve serious problem with output. I'm using Phi-3.1-mini-4k-instruct-Q4_K_M.gguf and when i ask it same algebra test question it never answers correctly, while in text-gen-webui or kobolt.cpp it always answers correctly. I tried everything, with promt template and without it. (<|system|> {system_prompt}<|end|><|user|> {prompt}<|end|><|assistant|>)
Tried both android version and windows version, both fail.
(i also tried to erase or turn off everything in maid character settings)
Question is: Two years ago, I was three times as old as my brother was. In three years, I will be twice as old as my brother. How old is each of us now?
Answer:  17 and 7
Here is how it answers correctly in text-generation-webui or koboltcpp:
Let's assume my current age is A and my brother's current age is B.
Two years ago, I was (A-2) years old and my brother was (B-2) years old.
According to the first statement, I was three times as old as my brother two years ago:
A - 2 = 3(B - 2)
Now, in three years, I will be (A+3) years old and my brother will be (B+3) years old.
According to the second statement, I will be twice as old as my brother in three years:
A + 3 = 2(B + 3)
Now we have two equations:
1) A - 2 = 3B - 6
2) A + 3 = 2B + 6
Let's solve the system of equations:
From equation 1:
A = 3B - 4
Substitute A in equation 2 with (3B - 4):
3B - 4 + 3 = 2B + 6
3B - 1 = 2B + 6
3B - 2B = 6 + 1
B = 7
Now that we have B, we can find A using the first equation:
A = 3B - 4
A = 3(7) - 4
A = 21 - 4
A = 17
So, currently, I am 17 years old and my brother is 7 years old.

Is it possible that the lack of instruct mode may be the problem?

**Comment by danemadsen** [comment]
I think the model just cant math

**Comment by mlsterpr0** [comment]
> I think the model just cant math

As i said, I'm 100% sure, that using the same gguf file in different apps gives different results. This model is very good at math. Why don't you try it yourself?
For example here: https://ai.azure.com/explore/models/Phi-3-mini-4k-instruct/version/9/registry/azureml (down on the right is where you enter promt).
Or anywhere you can run the model. Try the question i provided.

**Comment by Musabe24** [comment]
![Screenshot_20240708_214024.jpg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/98362464/8c946d9f-bc13-42d0-b445-be4c4f0c426c)

I am using the same model as in the screenshots on the main page. Always gettings strange answers.

**Comment by Musabe24** [comment]
> ![Screenshot_20240708_214024.jpg](https://github.com/Mobile-Artificial-Intelligence/maid/assets/98362464/8c946d9f-bc13-42d0-b445-be4c4f0c426c)
> 
> I am using the same model as in the screenshots on the main page. Always gettings strange answers.

Update:
I just saw there is a newer versions of the app here on github. I installed the app from f-droid first. After installing the version from github it solved the problem.
