### ISSUE TITLE
AppImage Launch Broken

### ISSUE THREAD

**Issue by GetGeit** [Mobile-Artificial-Intelligence/maid#586]
Issue with AppImage on launch.

**From Terminal**
`/tmp/.mount_maid.AakJnZM/AppRun: line 3: /home/runner/work/maid/maid/maid: No such file or directory`

**App Run**
```
#!/bin/bash
HERE="/home/runner/work/maid/maid"
exec "$HERE/maid" "$@"
```

Change line to
`HERE="$(dirname "$(readlink -f "${0}")")"`
?

**Comment by danemadsen** [comment]
does 1.2.8 work for you?

**Comment by danemadsen** [comment]
try this when you can

https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/9869164632

**Comment by GetGeit** [comment]
> does 1.2.8 work for you?

It does. 

1.2.9 also works with the edit.
