### ISSUE TITLE
Missing requirements 

### ISSUE THREAD

**Issue by Mikhail1711** [Mobile-Artificial-Intelligence/maid#588]
Llama CPP: 
- A path to the model file is required. 
- The file provided does not  exist. 

OpenAI & Mistral AI: 
 - A model option is required for prompting.
 - An authentification token is required for prompting. 

Ollama:
 - A model option is required for prompting.
 
Gemini:
 - An authentification token is required for prompting. 

Andriod 13

**Comment by fhnb16** [comment]
trying to connect to llamafile server on pc, same issue, just saying Missing requirements
