### ISSUE TITLE
Deleting chats individually is buddy

### ISSUE THREAD

**Issue by PrivacyOsint2** [Mobile-Artificial-Intelligence/maid#599]
Deleting chats individually is buddy, hit or miss when I try to delete on Mobile.

Example I hold one down the chat with my finger, let go. The delete button doesn't always show up. I have to do this 4-5 times to delete one chat.

Feature add:

Delete chat by swiping right as an option instead of hold down each chat section. Better UI functionality. 

![maid_4](https://github.com/user-attachments/assets/34310c68-2071-4504-b59d-1dbe36a943b5)

Look at this other project:

https://github.com/JHubi1/ollama-app

**Comment by danemadsen** [comment]
I don't like the idea of using dismissable on session tiles. Swiping is meant to close the drawer so adding swipe gestures to the session tiles makes things a little confusing. Ive lowered the long press timer from 1 second to .5 of a second so maybe that helps
