### ISSUE TITLE
Unable to create more characters

### ISSUE THREAD

**Issue by Pietro395** [Mobile-Artificial-Intelligence/maid#600]
If I click on the "Add" button in the character section, nothing happens.

I can only edit the "Maid" character, but every time the app is repainted this resets

Android 14 Graphene OS
Pixel 6a

**Comment by danemadsen** [comment]
Fixed this, will be in next update

**Comment by Pietro395** [comment]
> Fixed this, will be in next update

Is it fixed in version 1.3.1?
i tried but still have this problem

**Comment by danemadsen** [comment]
Oh i see what you mean now
