### ISSUE TITLE
Why not using GPU?

### ISSUE THREAD

**Issue by mmwong1984** [Mobile-Artificial-Intelligence/maid#602]
Hi! I have use this app to try running qwen 1.8b. However, I have discovered that seems this app is running AI models in CPU, but not GPU. This should be a bug as AI models should not run in a CPU. Please fix it so that we can enjoy the joy brought by AI.

**Comment by danemadsen** [comment]
I fixed vulkan support as of 1.3.1

**Comment by mmwong1984** [comment]
Still running on CPU

**Comment by mmwong1984** [comment]
@danemadsen
