### ISSUE TITLE
Make the default user profile gender-neutral.

### ISSUE THREAD

**Issue by tusharhero** [Mobile-Artificial-Intelligence/maid#606]
The current menu in the app shows a bearded man for the user's profile picture, it also doesn't have any female options in the defaults. I think for gender inclusivity we should have the gender-neutral profile as the default and also add female option in the defaults.

**Comment by tusharhero** [comment]
I think, we should at least change the default to the "gray person mascot".

**Comment by danemadsen** [comment]
No that's too bland. I don't mind adding gender neutral options for users but I like the default user profiles to have personality, and I really don't think genderless characters with no facial features are very appealing to anyone.

If you want me to provide some female options I can but the idea was for people to use their own images.

The other route I could go is provide inanimate objects as profile pictures much like apple and a fewothers do.

**Comment by tusharhero** [comment]
I don't think everyone wants to be a bearded man though, if the user wants to have a separate profile they can easily add it. I think the animate profile pictures idea is great too.

**Comment by danemadsen** [comment]
Yes I understand that. There's definitely women that use this app that I know of. But like I said, I like the profiles to have atleast some personality. I chose that profile because it contrasted the default maid character the best.

I think the Inanimate objects approach is

**Comment by danemadsen** [comment]
Temporarily fixed this not sure if ill keep it permanent though.

**Comment by ILOVEPIE** [comment]
> Temporarily fixed this not sure if ill keep it permanent though.

One way to fix this would be to do a split on the image of a maid outfit and a butler outfit.
