### ISSUE TITLE
Cannot run on version 1.3.0 (Windows)

### ISSUE THREAD

**Issue by NightHanter** [Mobile-Artificial-Intelligence/maid#610]
I tried running version 1.3.0 on three different pc's, (win11 and win10) and everywhere had the same result, the application appears in task manager with zero CPU load and RAM consumption at ~34 mb, and it doesn't disappear from there except manually terminating the task. I have win11 23H2, ryzen 5 5600+32 ram, rtx3060 in my pc. Other computers I have tried to run the program on are ryzen 3 3250u+20 ram, win11, and intel pentium gold g6400 4 gb ram win10. Everywhere I got the same result - no reaction to trying to run maid.exe from the 1.3.0 release zip archive. Trying to install version 1.2.9 led to the fact that on all PCs the program started, but when loading gemma-2-2-2b-it-abliterated-Q6_K_L.gguf the program crashed without any errors on all three computers. Version 1.3.0 at the same time works on the phone without any problems. (poco x3 nfc, the same model I tried to use on the PC). The gpu drivers are updated to the latest version, visual c++ is also completely updated, Python 3.10.6 is installed in the system. The folder with the program is added to antivirus exceptions. The folder with the program is located at "F:\LLM_AI\Maid".

**Comment by danemadsen** [comment]
Ok, I'm going to guess it's a similar issue to #609

**Comment by danemadsen** [comment]
This should be fixed now as of this build https://github.com/Mobile-Artificial-Intelligence/maid/actions/runs/10537373610

If its not ping me and ill reopen it.
