### ISSUE TITLE
Replace project's logo/icon to represent something else other than the AI as a "maid"

### ISSUE THREAD

**Issue by pedrorocha-net** [Mobile-Artificial-Intelligence/maid#620]
First of all, congrats you all on the awesome project! That is really the future of AI, to be on mobile phones.

Exactly because it's such a leap into the future, we could take the chance to replace bad-old habits like reinforcing the image of having women as servants, specially with an image that even sexualize a bit the character.

What about considering a new logo?

**Comment by WizCoderr** [comment]
I can do it very easily can you please assign it to me under hacktoberfest label
